# Homework: Numpy, Covariance

In this assignment, you're primarily just reading, with a small amount of work to do in the end.  This is a basic numpy tutorial.

### Extra resources, if you want them (not required reading/viewing)
* The [official numpy tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* Jake Vanderplas' book has an [entire chapter on numpy](https://github.com/jakevdp/PythonDataScienceHandbook)
* The rest of the [excellent youtube video series on Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

In [2]:
import numpy as np
import pandas as pd

The primarily object in numpy is the `array`, which is a fast, multidimensional, single-data-type array:

In [29]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])

print(a.shape, b.shape)

(3,) (2, 3)


Because they're multidimensional, we can slice them in multiple dimensions:

In [4]:
# Define a method for printing out arrays with an extra newline at the end, for readability
zprint = lambda *x: print(*x, end='\n\n')

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

zprint(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]


In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
zprint(a)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
zprint(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
zprint(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
zprint(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                            #          [ 6]
                            #          [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[5 6 7 8] (4,)

[[5 6 7 8]] (1, 4)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


You can perform basic mathematical operations on arrays

In [8]:
x = np.array([[1,2],[3,4], [6,5]])
y = np.array([[5,6],[7,8]])

zprint(x)
zprint(y)
# zprint(x + y)
# zprint(y - x)
# zprint(x * y)
# zprint(y / x)
print(np.sqrt(x))

[[1 2]
 [3 4]
 [6 5]]

[[5 6]
 [7 8]]

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]
 [ 2.44948974  2.23606798]]


Are these what you expect?  If you're thinking of a numpy array as a matrix, `a * b` gives us the "wrong" answer, and `b/a` doesn't really even make sense.  These are _elementwise_ computations!  Keep that in mind.

In [10]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner / dot product of vectors; both produce 219
zprint(v.dot(w))
zprint(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
zprint(x.dot(v))
zprint(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
# x:
# [[1 2]
#  [3 4]]
# y:
# [[5 6]
#  [7 8]]
zprint(x)
zprint(y)
zprint(x.dot(y))
print(np.dot(x, y))

219

219

[29 67]

[29 67]

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


Recall that the **transpose** of a matrix is the the result of reflecting it on the diagonal:

In [11]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])

zprint(z)
print(z.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Finally, the **determinant** of a matrix is a single-number quantity that has a lot of uses.  It has a nice [geometric interpretation](https://www.youtube.com/watch?v=Ip3X9LOh2dk) (10 minute video, not required watching), and it also has the following property:

**If $A$ is a matrix with the property that some non-zero vector $v$ gives the equation $Av = 0$, then $det(A)=0$.**

The definition of the determinant is a little clunky, and I won't require you to know it (at least, not for this test).  But that's what computers are for!

In [14]:
print("Determinants:")
for s, d in [(s, np.linalg.det(s)) for s in [x, y, z]]:
    zprint(s, "--->", d)

Determinants:
[[1 2]
 [3 4]] ---> -2.0

[[5 6]
 [7 8]] ---> -2.0

[[1 2 3]
 [4 5 6]
 [7 8 9]] ---> -9.51619735393e-16



<div style="background-color: #EFDDFF; ">

<p> Now, it's your turn: **Write a function** that uses the above commands as well as `np.mean` to create, by hand, the covariance matrix of a dataset.  What's that, you might ask.  For now, let's just work with the definition and how to compute (more for practice with numpy than anything else), and tomorrow we'll cover what it is and how it relates to everything else. </p>

Given two columns of data (a statistician would call them _random vectors_), the __covariance__ of the pair is a quantity that captures the amount they _vary together_:

$$cov(x,y) = \frac{1}{n}\sum_{i=1}^n (x_i-\overline{x})(y_i-\overline{y})$$

Given a dataset, you could consider taking the covariance of every pair of columns, and somehow comparing them.  The most sensible thing to do for storing those covariances would be in a matrix, called the [__covariance matrix__](https://en.wikipedia.org/wiki/Covariance_matrix): 

$$\Sigma = \left(\begin{array}{cccc}
cov(x_1,x_1) & cov(x_1,x_2) & \dots & cov(x_1,x_n) \\
cov(x_2,x_1) & cov(x_2,x_2) & \dots & cov(x_2,x_n) \\
\vdots & \vdots & \ddots & \vdots \\
cov(x_n,x_1) & cov(x_n,x_2) & \dots & cov(x_n,x_n) \\
\end{array}\right)$$
</div>

In [72]:
a = np.array([[1,2],[3,4]])
a+2

array([[3, 4],
       [5, 6]])

In [73]:
v = np.array([[6,7]])
a+v.T

array([[ 7,  8],
       [10, 11]])

In [69]:
# Your code here! (It shouldn't be nearly as scary as it looks! Right a 
# covariance method, and then use a nested list comprehension or a nested 
# for loop to build the matrix.)

# def covariance(x, y):
#     _sum = 0
#     for i in range(len(x)):
#         _sum += (x[i] - np.mean(x)) * (y[i] - np.mean(y))
#     return _sum / len(x)

def covariance(x, y):
    return np.mean((x-np.mean(x)) * (y - np.mean(y)))

def covariance2D(x):
    m = [[0 for x in range(len(x[0]))] for y in range(len(x[0]))] 
    for i in range(len(x[0])):
        for j in range(len(x[0])):
            m[i][j] = covariance(x[:, i], x[:, j])
    return np.array(m)

<div style="background-color: #EFDDFF; ">
After writing the method, **first** test it out on the following matrix. Don't worry about the strange keyword arguments to `np.cov`, it makes different assumptions about the dataset than we do.
</div>

In [70]:
np.random.seed(seed=1863)
x = np.random.randint(-10, 10, size=(3,3))
zprint(covariance2D(x))
print("Original matrix:", x.T, '', "Its covariance matrix:", np.cov(x, rowvar=False, bias=1), sep='\n')

[[  8.  -8.   6.]
 [ -8.   8.  -6.]
 [  6.  -6.  42.]]

Original matrix:
[[  0   6   0]
 [  5  -1   5]
 [-10   2   5]]

Its covariance matrix:
[[  8.  -8.   6.]
 [ -8.   8.  -6.]
 [  6.  -6.  42.]]


<div style="background-color: #EFDDFF; ">
**Second**, compute the covariance matrix for [this dataset](https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv), which is [explained here](https://vincentarelbundock.github.io/Rdatasets/doc/datasets/mtcars.html).  To do this into numpy, the fastest way is to go through Pandas to read the csv, then take `df.values` on the dataframe that you get.
</div>

In [71]:
df = pd.read_csv("data/mtcars.csv", header=1)
print(df)
values = df.values[:,1:]
print(covariance2D(a))

              Mazda RX4    21  6    160  110   3.9   2.62  16.46  0  1  4  4.1
0         Mazda RX4 Wag  21.0  6  160.0  110  3.90  2.875  17.02  0  1  4    4
1            Datsun 710  22.8  4  108.0   93  3.85  2.320  18.61  1  1  4    1
2        Hornet 4 Drive  21.4  6  258.0  110  3.08  3.215  19.44  1  0  3    1
3     Hornet Sportabout  18.7  8  360.0  175  3.15  3.440  17.02  0  0  3    2
4               Valiant  18.1  6  225.0  105  2.76  3.460  20.22  1  0  3    1
5            Duster 360  14.3  8  360.0  245  3.21  3.570  15.84  0  0  3    4
6             Merc 240D  24.4  4  146.7   62  3.69  3.190  20.00  1  0  4    2
7              Merc 230  22.8  4  140.8   95  3.92  3.150  22.90  1  0  4    2
8              Merc 280  19.2  6  167.6  123  3.92  3.440  18.30  1  0  4    4
9             Merc 280C  17.8  6  167.6  123  3.92  3.440  18.90  1  0  4    4
10           Merc 450SE  16.4  8  275.8  180  3.07  4.070  17.40  0  0  3    3
11           Merc 450SL  17.3  8  275.8  180  3.07  

# Just for your learning purposes, here's how I found a 3x3 integer-valued matrix with an integer-valued covariance matrix:

In [68]:
for i in range(100000):
    if i == 883:
        # This one is trivial
        continue
    np.random.seed(seed=i)
    x = np.random.randint(-10, 10, size=(3,3))
    cov = np.cov(x, rowvar=False, bias=1)
    if (cov.round() == cov).all():
        print(i, x, cov, sep='\n\n')
        break

1863

[[  0   5 -10]
 [  6  -1   2]
 [  0   5   5]]

[[  8.  -8.   6.]
 [ -8.   8.  -6.]
 [  6.  -6.  42.]]
